os:
  - linux

language: node_js

node_js:
  - '0.12'
  - lts/*
  - stable
  - unstable


before_install:
  - npm install -g npm@latest

script:
  - npm run-script test-travis
  - npm run-script test-sauce

after_script:
  - npm install coveralls@2 && cat ./coverage/lcov.info | coveralls


env:
  global:
    - secure: m6jfvo/eAous50Tpk82tnj3S6zPVmntSd+jJaNWzDHvaoIAGxCQ6AFba4w55XBRzFDFOBrio0QryR70ZztuXK0l0az8ACMTPh+kgG65VYcc3nQ4LBtyVTeBtQvtXKpnakbP0EeQ1cgNYAaSK692rv+Yx3jsU3cxEVLC9mErIubmvhQpqyYaPnfjlciBkCHIJK8ICQoMWUgRhdp7nwH63Z2KU/ABSw3vQIKiDZQ/DLp5HC28NoOVPYyTrwvGrNfrxISys1ANM2EZr8GWEuUbT4Ta2bmQlStMuZmuQVcwuKSF64md42dYCDBLmdD4jvFF02oSJp6mBZ0ruNx2IIOxacCzK8QU6DhOnvGgKNgWw+9FRj/duVg0QCNimsXJulUbCdwLB2A2F3bHIJkwaq0T7b5MJQVjNx3yzkdCKL8gogssqA8gRyzk44e4iDxwgH0XAagvEUPlJctT8YVHMCRYWR7dBJlaZsmIkBdvmrTQR6pMPQoOEqTVNrDw78GdNQsf2ZYwaqaxMA73TvxeW6Nb8Tmk6O/fjlxBuD/NkH/DRR79q0sb6r7TDzkLNxkF4MpYVVKeYE4jQrlC1NeAFCDWknABw7o4NBc2Zcv2V1oFeruy5+i1JQycl+p2FARfR/j+ySqGFYxqk19tAojFbmpp6W8rYBJgFM05nrFXZP53eobc=
    - secure: xy9MIpgYnjhQ4oW7LsZFxeiTtYRznb8NI4J+SVngNBJpjrGAGJtsJr4vVv7pzRxetb3T8+sAhSeIwRt/1sLwdLxyjPu6v5+O/25OQvDkV1NQRCLceQAahNZRHy2K3KqiJcYR02iLIcB/5FdUet1eyDIlbxu/nepIMmLv7G0EjQjDlPKPLN+nX/NqBkBfHIt0XPqUINenC8aS+XCQaXktYqvamWavf9yT3Y7Mwna3Qw9y8lW50dcVstk83bhMtfmIKylIwE+fAUkm56YbSybNfPE54ppem3Y97QBTb8vGN0ic8RkWmh9fNeUJGHHGvEWBAxWKdVb4RGozc7Oc0Lz341I/9mVHdJ7DWUbWmLv6ETiIXUxwM8gj0NeEMez79e2383m4/+Ne0wKfaQbc5RBhIoUCzuAfNU8Mv7tuMEcktLokZ26EJwYVJkGeCkyUNfn7DZNyaduH+Pu6VHkKMzkyuEqwkWC6haIGE+SiXdTV+meW1YtIeCXyvxgFBBtbfjmyyEN++zEpb4EtQJzB5E7iQHYyicj1SRRXR5AYm4a0lAd236A6jNsulsD4FpCbB3koVyjC6ANTPfTtCgXLqfjDO1lU6RJPQayBdCxHWepOExZ8bDyWTEtcMMtvXt1Y97EUmmhA5SxLP3jVNqe3MX9H8ktXAIso9nSzCqf7KV2f6ro=
